### ISSUE TITLE
Empty attributes show for filtering

### ISSUE THREAD

**Issue by jeking928** [Zen4All/Zen-Cart_Dynamic_Attribute_filter#5]
Maybe I just don't understand. It appears as if attributes that do not apply to the current products being viewed are being shown in the left column.  See screenshot
![image](https://cloud.githubusercontent.com/assets/8162029/6423727/daefbba2-beaf-11e4-87bf-15ff24529cd2.png)
I realize I can exclude attributes by ID, which does work and it fabulous, but shouldn't attributes with no option _not_ display at all?

**Comment by Zen4All** [comment]
I have not seen that before, Can you explain a bit more how those attributes are set up? Maybe mail me a link to your site?

**Comment by jeking928** [comment]
This is a stock 1.5.4 cart with the sample products. Currently at:
http://www.wheatonwebsiteservices.com/zen154/index.php?main_page=index&cPath=22

**Comment by Zen4All** [comment]
Good catch, I see them to in my test site. Those are text attributes.
I think text attributes can be excluded form the menu. They have IMHO no value searching for products while using the filter.
I will put up a test with a query excluding text attributes.

**Comment by jeking928** [comment]
I would agree about excluding them, seems no downside to that at all.

**Comment by Zen4All** [comment]
Ok I updated the query on my test site and it works fine. Also excluded the file type attribute

**Comment by Zen4All** [comment]
Also fixed in the master repo now.

**Comment by jeking928** [comment]
Very nice, I'll test and let you know if I find any other issues.

**Comment by Zen4All** [comment]
I think there is at least one, when the category filter is disabled, but will open a new issue for that

**Comment by jeking928** [comment]
I'll wait for you to open the issue, but I don't see the sidebox on category pages with the option set to Yes.  Everything else I've checked is working fine!
